### ISSUE TITLE
vRTracker program

### ISSUE THREAD

**Issue by choywin** [Archer-Tatsu/VRTracker#1]
Hello,

This program sounds very useful and I am trying to run your VRTracker program. I have already modified all paths of SDK following your adding paths (i.e.openVR and aglass) included and I can build the program without error. However, I type the command in cmd console following your guideline, i.e. "VRTracker.exe D:\temp try video1 5.041". But it shows an application error message: "The application was unable to start correctly(0xc000007b). click OK to close athe application".

I also tried to use "VRtracker.cpp" only to run and also use "vRtracker_control.cpp" to run together, but it also failed.

Any hint to solve this problem? Looking forward to your reply.

**Comment by MasterMurphy** [comment]
Total noob here—What do I change the #include file paths to? I cannot find aGlass_vr_api.h anywhere, and openvr.h is a dynamically generated file, no? I don't understand where these files should be! Thanks

**Comment by Archer-Tatsu** [comment]
Sorry for the late reply.
@choywin Sorry, the readme.md is out-of-date. There is a another argument needed: frame rate. 
https://github.com/Archer-Tatsu/VRTracker/blob/679a411c95ec145e232676d4f9c0ba48701b6105/test/VRTracker.cpp#L79
Besides, make sure you have the hardware (especially the aGlass module required for eye tracking).

@MasterMurphy 
_aGlass_  is an extramodule for eye tracking for HTC Vive. The files can be founded in their SDK.
More about OpenVR and aGlass:
https://github.com/ValveSoftware/openvr
http://www.aglass.com/?lang=en
